name: Docker Image CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          content=$(jq -r 'tostring' release.json)
          echo "::set-output name=matrix::$content"
          echo "--------------------------------------"
          echo ${{ steps.set-matrix.outputs.matrix }}

  build:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          if ${{ matrix.latest }}; then
            docker build . --file ${{ matrix.binary_version }}/${{ matrix.platform }}/Dockerfile --tag ${{ matrix.binary_version }}:${{ matrix.platform }}, latest
          else
            docker build . --file ${{ matrix.binary_version }}/${{ matrix.platform }}/Dockerfile --tag ${{ matrix.binary_version }}:${{ matrix.platform }}
          fi
