name: Docker Buld and Run tests

on:
  pull_request:
    branches: [master]

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          content=$(jq -r 'tostring' release.json)
          echo "::set-output name=matrix::$content"
          echo ${{ steps.set-matrix.outputs.matrix }}

  tests:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v2
      - name: Build and run test
        run: |
          export BINARY=${{ matrix.binary_version }}
          export PLATFORM=${{ matrix.os }}
          docker-compose --file ./tests/docker-compose.test.yml build
          docker-compose --file ./tests/docker-compose.test.yml run sut
