name: Docker Image CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [master]

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the matrix 
        run: |
          echo $(ls -a)
          content=$(cat ./release.json)
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=matrix::$content"

  build:
    needs: generate_matrix 
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ${{ matrix.binary_version }}/${{ matrix.platform }}/Dockerfile --tag ${{ matrix.binary_version }}:${{ matrix.platform }}
